version: '3'

services:

  server-a:
    build: ./server-a
    container_name: server-a

  server-b:
    build: ./server-b
    container_name: server-b

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - server-a
      - server-b
  
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - server-a
      - server-b

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"